// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// NewCreateProviderConfigurationParams creates a new CreateProviderConfigurationParams object
// no default values defined in spec.
func NewCreateProviderConfigurationParams() CreateProviderConfigurationParams {

	return CreateProviderConfigurationParams{}
}

// CreateProviderConfigurationParams contains all the bound params for the create provider configuration operation
// typically these are obtained from a http.Request
//
// swagger:parameters create-provider-configuration
type CreateProviderConfigurationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Terraform Provider Name
	  Required: true
	  In: path
	*/
	ProviderName string
	/*A terraform module
	  In: body
	*/
	TerraformProviderConfiguration *models.ResourceTfProviderConfiguration
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateProviderConfigurationParams() beforehand.
func (o *CreateProviderConfigurationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rProviderName, rhkProviderName, _ := route.Params.GetOK("provider-name")
	if err := o.bindProviderName(rProviderName, rhkProviderName, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ResourceTfProviderConfiguration
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("terraformProviderConfiguration", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.TerraformProviderConfiguration = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindProviderName binds and validates parameter ProviderName from path.
func (o *CreateProviderConfigurationParams) bindProviderName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ProviderName = raw

	return nil
}
