// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteProviderConfigurationParams creates a new DeleteProviderConfigurationParams object
// no default values defined in spec.
func NewDeleteProviderConfigurationParams() DeleteProviderConfigurationParams {

	return DeleteProviderConfigurationParams{}
}

// DeleteProviderConfigurationParams contains all the bound params for the delete provider configuration operation
// typically these are obtained from a http.Request
//
// swagger:parameters delete-provider-configuration
type DeleteProviderConfigurationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Configuration for a Terraform Provider
	  Required: true
	  In: path
	*/
	ID string
	/*Terraform Provider ID
	  Required: true
	  In: path
	*/
	ProviderName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteProviderConfigurationParams() beforehand.
func (o *DeleteProviderConfigurationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	rProviderName, rhkProviderName, _ := route.Params.GetOK("provider-name")
	if err := o.bindProviderName(rProviderName, rhkProviderName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindID binds and validates parameter ID from path.
func (o *DeleteProviderConfigurationParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ID = raw

	return nil
}

// bindProviderName binds and validates parameter ProviderName from path.
func (o *DeleteProviderConfigurationParams) bindProviderName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ProviderName = raw

	return nil
}
