// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// DeleteProviderConfigurationHandlerFunc turns a function with the right signature into a delete provider configuration handler
type DeleteProviderConfigurationHandlerFunc func(DeleteProviderConfigurationParams, *models.ResourceAuthUser) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteProviderConfigurationHandlerFunc) Handle(params DeleteProviderConfigurationParams, principal *models.ResourceAuthUser) middleware.Responder {
	return fn(params, principal)
}

// DeleteProviderConfigurationHandler interface for that can handle valid delete provider configuration params
type DeleteProviderConfigurationHandler interface {
	Handle(DeleteProviderConfigurationParams, *models.ResourceAuthUser) middleware.Responder
}

// NewDeleteProviderConfiguration creates a new http.Handler for the delete provider configuration operation
func NewDeleteProviderConfiguration(ctx *middleware.Context, handler DeleteProviderConfigurationHandler) *DeleteProviderConfiguration {
	return &DeleteProviderConfiguration{Context: ctx, Handler: handler}
}

/*DeleteProviderConfiguration swagger:route DELETE /tf/provider/{provider-name}/configuration/{id} providers deleteProviderConfiguration

Delete a terraform provider configuration

*/
type DeleteProviderConfiguration struct {
	Context *middleware.Context
	Handler DeleteProviderConfigurationHandler
}

func (o *DeleteProviderConfiguration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteProviderConfigurationParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.ResourceAuthUser
	if uprinc != nil {
		principal = uprinc.(*models.ResourceAuthUser) // this is really a models.ResourceAuthUser, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
