// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// GetProviderHandlerFunc turns a function with the right signature into a get provider handler
type GetProviderHandlerFunc func(GetProviderParams, *models.ResourceAuthUser) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProviderHandlerFunc) Handle(params GetProviderParams, principal *models.ResourceAuthUser) middleware.Responder {
	return fn(params, principal)
}

// GetProviderHandler interface for that can handle valid get provider params
type GetProviderHandler interface {
	Handle(GetProviderParams, *models.ResourceAuthUser) middleware.Responder
}

// NewGetProvider creates a new http.Handler for the get provider operation
func NewGetProvider(ctx *middleware.Context, handler GetProviderHandler) *GetProvider {
	return &GetProvider{Context: ctx, Handler: handler}
}

/*GetProvider swagger:route GET /tf/provider/{name} providers getProvider

Get Terraform Provider

*/
type GetProvider struct {
	Context *middleware.Context
	Handler GetProviderHandler
}

func (o *GetProvider) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetProviderParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.ResourceAuthUser
	if uprinc != nil {
		principal = uprinc.(*models.ResourceAuthUser) // this is really a models.ResourceAuthUser, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
