// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/getlunaform/lunaform/models"
)

// GetProviderConfigurationNotFoundCode is the HTTP code returned for type GetProviderConfigurationNotFound
const GetProviderConfigurationNotFoundCode int = 404

/*GetProviderConfigurationNotFound Not Found

swagger:response getProviderConfigurationNotFound
*/
type GetProviderConfigurationNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ServerError `json:"body,omitempty"`
}

// NewGetProviderConfigurationNotFound creates GetProviderConfigurationNotFound with default headers values
func NewGetProviderConfigurationNotFound() *GetProviderConfigurationNotFound {

	return &GetProviderConfigurationNotFound{}
}

// WithPayload adds the payload to the get provider configuration not found response
func (o *GetProviderConfigurationNotFound) WithPayload(payload *models.ServerError) *GetProviderConfigurationNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get provider configuration not found response
func (o *GetProviderConfigurationNotFound) SetPayload(payload *models.ServerError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProviderConfigurationNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetProviderConfigurationInternalServerErrorCode is the HTTP code returned for type GetProviderConfigurationInternalServerError
const GetProviderConfigurationInternalServerErrorCode int = 500

/*GetProviderConfigurationInternalServerError Internal Server Error

swagger:response getProviderConfigurationInternalServerError
*/
type GetProviderConfigurationInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServerError `json:"body,omitempty"`
}

// NewGetProviderConfigurationInternalServerError creates GetProviderConfigurationInternalServerError with default headers values
func NewGetProviderConfigurationInternalServerError() *GetProviderConfigurationInternalServerError {

	return &GetProviderConfigurationInternalServerError{}
}

// WithPayload adds the payload to the get provider configuration internal server error response
func (o *GetProviderConfigurationInternalServerError) WithPayload(payload *models.ServerError) *GetProviderConfigurationInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get provider configuration internal server error response
func (o *GetProviderConfigurationInternalServerError) SetPayload(payload *models.ServerError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProviderConfigurationInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
