// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/getlunaform/lunaform/models"
)

// ListProviderConfigurationsNotFoundCode is the HTTP code returned for type ListProviderConfigurationsNotFound
const ListProviderConfigurationsNotFoundCode int = 404

/*ListProviderConfigurationsNotFound Not Found

swagger:response listProviderConfigurationsNotFound
*/
type ListProviderConfigurationsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ServerError `json:"body,omitempty"`
}

// NewListProviderConfigurationsNotFound creates ListProviderConfigurationsNotFound with default headers values
func NewListProviderConfigurationsNotFound() *ListProviderConfigurationsNotFound {

	return &ListProviderConfigurationsNotFound{}
}

// WithPayload adds the payload to the list provider configurations not found response
func (o *ListProviderConfigurationsNotFound) WithPayload(payload *models.ServerError) *ListProviderConfigurationsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list provider configurations not found response
func (o *ListProviderConfigurationsNotFound) SetPayload(payload *models.ServerError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProviderConfigurationsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListProviderConfigurationsInternalServerErrorCode is the HTTP code returned for type ListProviderConfigurationsInternalServerError
const ListProviderConfigurationsInternalServerErrorCode int = 500

/*ListProviderConfigurationsInternalServerError Internal Server Error

swagger:response listProviderConfigurationsInternalServerError
*/
type ListProviderConfigurationsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServerError `json:"body,omitempty"`
}

// NewListProviderConfigurationsInternalServerError creates ListProviderConfigurationsInternalServerError with default headers values
func NewListProviderConfigurationsInternalServerError() *ListProviderConfigurationsInternalServerError {

	return &ListProviderConfigurationsInternalServerError{}
}

// WithPayload adds the payload to the list provider configurations internal server error response
func (o *ListProviderConfigurationsInternalServerError) WithPayload(payload *models.ServerError) *ListProviderConfigurationsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list provider configurations internal server error response
func (o *ListProviderConfigurationsInternalServerError) SetPayload(payload *models.ServerError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProviderConfigurationsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
