// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/getlunaform/lunaform/models"
)

// ListProvidersOKCode is the HTTP code returned for type ListProvidersOK
const ListProvidersOKCode int = 200

/*ListProvidersOK OK

swagger:response listProvidersOK
*/
type ListProvidersOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseListTfProviders `json:"body,omitempty"`
}

// NewListProvidersOK creates ListProvidersOK with default headers values
func NewListProvidersOK() *ListProvidersOK {

	return &ListProvidersOK{}
}

// WithPayload adds the payload to the list providers o k response
func (o *ListProvidersOK) WithPayload(payload *models.ResponseListTfProviders) *ListProvidersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list providers o k response
func (o *ListProvidersOK) SetPayload(payload *models.ResponseListTfProviders) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProvidersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListProvidersInternalServerErrorCode is the HTTP code returned for type ListProvidersInternalServerError
const ListProvidersInternalServerErrorCode int = 500

/*ListProvidersInternalServerError Internal Server Error

swagger:response listProvidersInternalServerError
*/
type ListProvidersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServerError `json:"body,omitempty"`
}

// NewListProvidersInternalServerError creates ListProvidersInternalServerError with default headers values
func NewListProvidersInternalServerError() *ListProvidersInternalServerError {

	return &ListProvidersInternalServerError{}
}

// WithPayload adds the payload to the list providers internal server error response
func (o *ListProvidersInternalServerError) WithPayload(payload *models.ServerError) *ListProvidersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list providers internal server error response
func (o *ListProvidersInternalServerError) SetPayload(payload *models.ServerError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListProvidersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
