// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// CreateProviderReader is a Reader for the CreateProvider structure.
type CreateProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateProviderCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateProviderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateProviderCreated creates a CreateProviderCreated with default headers values
func NewCreateProviderCreated() *CreateProviderCreated {
	return &CreateProviderCreated{}
}

/*CreateProviderCreated handles this case with default header values.

OK
*/
type CreateProviderCreated struct {
	Payload *models.ResourceTfProvider
}

func (o *CreateProviderCreated) Error() string {
	return fmt.Sprintf("[POST /tf/providers/][%d] createProviderCreated  %+v", 201, o.Payload)
}

func (o *CreateProviderCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceTfProvider)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProviderBadRequest creates a CreateProviderBadRequest with default headers values
func NewCreateProviderBadRequest() *CreateProviderBadRequest {
	return &CreateProviderBadRequest{}
}

/*CreateProviderBadRequest handles this case with default header values.

Bad Request
*/
type CreateProviderBadRequest struct {
	Payload *models.ServerError
}

func (o *CreateProviderBadRequest) Error() string {
	return fmt.Sprintf("[POST /tf/providers/][%d] createProviderBadRequest  %+v", 400, o.Payload)
}

func (o *CreateProviderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
