// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// NewCreateProviderConfigurationParams creates a new CreateProviderConfigurationParams object
// with the default values initialized.
func NewCreateProviderConfigurationParams() *CreateProviderConfigurationParams {
	var ()
	return &CreateProviderConfigurationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateProviderConfigurationParamsWithTimeout creates a new CreateProviderConfigurationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateProviderConfigurationParamsWithTimeout(timeout time.Duration) *CreateProviderConfigurationParams {
	var ()
	return &CreateProviderConfigurationParams{

		timeout: timeout,
	}
}

// NewCreateProviderConfigurationParamsWithContext creates a new CreateProviderConfigurationParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateProviderConfigurationParamsWithContext(ctx context.Context) *CreateProviderConfigurationParams {
	var ()
	return &CreateProviderConfigurationParams{

		Context: ctx,
	}
}

// NewCreateProviderConfigurationParamsWithHTTPClient creates a new CreateProviderConfigurationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateProviderConfigurationParamsWithHTTPClient(client *http.Client) *CreateProviderConfigurationParams {
	var ()
	return &CreateProviderConfigurationParams{
		HTTPClient: client,
	}
}

/*CreateProviderConfigurationParams contains all the parameters to send to the API endpoint
for the create provider configuration operation typically these are written to a http.Request
*/
type CreateProviderConfigurationParams struct {

	/*ProviderConfiguration
	  A terraform provider configuration

	*/
	ProviderConfiguration *models.ResourceTfProviderConfiguration
	/*ProviderName
	  Terraform Provider Name

	*/
	ProviderName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create provider configuration params
func (o *CreateProviderConfigurationParams) WithTimeout(timeout time.Duration) *CreateProviderConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create provider configuration params
func (o *CreateProviderConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create provider configuration params
func (o *CreateProviderConfigurationParams) WithContext(ctx context.Context) *CreateProviderConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create provider configuration params
func (o *CreateProviderConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create provider configuration params
func (o *CreateProviderConfigurationParams) WithHTTPClient(client *http.Client) *CreateProviderConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create provider configuration params
func (o *CreateProviderConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProviderConfiguration adds the providerConfiguration to the create provider configuration params
func (o *CreateProviderConfigurationParams) WithProviderConfiguration(providerConfiguration *models.ResourceTfProviderConfiguration) *CreateProviderConfigurationParams {
	o.SetProviderConfiguration(providerConfiguration)
	return o
}

// SetProviderConfiguration adds the providerConfiguration to the create provider configuration params
func (o *CreateProviderConfigurationParams) SetProviderConfiguration(providerConfiguration *models.ResourceTfProviderConfiguration) {
	o.ProviderConfiguration = providerConfiguration
}

// WithProviderName adds the providerName to the create provider configuration params
func (o *CreateProviderConfigurationParams) WithProviderName(providerName string) *CreateProviderConfigurationParams {
	o.SetProviderName(providerName)
	return o
}

// SetProviderName adds the providerName to the create provider configuration params
func (o *CreateProviderConfigurationParams) SetProviderName(providerName string) {
	o.ProviderName = providerName
}

// WriteToRequest writes these params to a swagger request
func (o *CreateProviderConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ProviderConfiguration != nil {
		if err := r.SetBodyParam(o.ProviderConfiguration); err != nil {
			return err
		}
	}

	// path param provider-name
	if err := r.SetPathParam("provider-name", o.ProviderName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
