// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// NewCreateProviderParams creates a new CreateProviderParams object
// with the default values initialized.
func NewCreateProviderParams() *CreateProviderParams {
	var ()
	return &CreateProviderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateProviderParamsWithTimeout creates a new CreateProviderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateProviderParamsWithTimeout(timeout time.Duration) *CreateProviderParams {
	var ()
	return &CreateProviderParams{

		timeout: timeout,
	}
}

// NewCreateProviderParamsWithContext creates a new CreateProviderParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateProviderParamsWithContext(ctx context.Context) *CreateProviderParams {
	var ()
	return &CreateProviderParams{

		Context: ctx,
	}
}

// NewCreateProviderParamsWithHTTPClient creates a new CreateProviderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateProviderParamsWithHTTPClient(client *http.Client) *CreateProviderParams {
	var ()
	return &CreateProviderParams{
		HTTPClient: client,
	}
}

/*CreateProviderParams contains all the parameters to send to the API endpoint
for the create provider operation typically these are written to a http.Request
*/
type CreateProviderParams struct {

	/*TerraformProvider
	  A terraform module

	*/
	TerraformProvider *models.ResourceTfProvider

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create provider params
func (o *CreateProviderParams) WithTimeout(timeout time.Duration) *CreateProviderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create provider params
func (o *CreateProviderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create provider params
func (o *CreateProviderParams) WithContext(ctx context.Context) *CreateProviderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create provider params
func (o *CreateProviderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create provider params
func (o *CreateProviderParams) WithHTTPClient(client *http.Client) *CreateProviderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create provider params
func (o *CreateProviderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTerraformProvider adds the terraformProvider to the create provider params
func (o *CreateProviderParams) WithTerraformProvider(terraformProvider *models.ResourceTfProvider) *CreateProviderParams {
	o.SetTerraformProvider(terraformProvider)
	return o
}

// SetTerraformProvider adds the terraformProvider to the create provider params
func (o *CreateProviderParams) SetTerraformProvider(terraformProvider *models.ResourceTfProvider) {
	o.TerraformProvider = terraformProvider
}

// WriteToRequest writes these params to a swagger request
func (o *CreateProviderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.TerraformProvider != nil {
		if err := r.SetBodyParam(o.TerraformProvider); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
