// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// DeleteProviderReader is a Reader for the DeleteProvider structure.
type DeleteProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteProviderNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteProviderNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewDeleteProviderMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewDeleteProviderUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteProviderInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteProviderNoContent creates a DeleteProviderNoContent with default headers values
func NewDeleteProviderNoContent() *DeleteProviderNoContent {
	return &DeleteProviderNoContent{}
}

/*DeleteProviderNoContent handles this case with default header values.

No Content
*/
type DeleteProviderNoContent struct {
}

func (o *DeleteProviderNoContent) Error() string {
	return fmt.Sprintf("[DELETE /tf/provider/{name}][%d] deleteProviderNoContent ", 204)
}

func (o *DeleteProviderNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProviderNotFound creates a DeleteProviderNotFound with default headers values
func NewDeleteProviderNotFound() *DeleteProviderNotFound {
	return &DeleteProviderNotFound{}
}

/*DeleteProviderNotFound handles this case with default header values.

Not Found
*/
type DeleteProviderNotFound struct {
	Payload *models.ServerError
}

func (o *DeleteProviderNotFound) Error() string {
	return fmt.Sprintf("[DELETE /tf/provider/{name}][%d] deleteProviderNotFound  %+v", 404, o.Payload)
}

func (o *DeleteProviderNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProviderMethodNotAllowed creates a DeleteProviderMethodNotAllowed with default headers values
func NewDeleteProviderMethodNotAllowed() *DeleteProviderMethodNotAllowed {
	return &DeleteProviderMethodNotAllowed{}
}

/*DeleteProviderMethodNotAllowed handles this case with default header values.

Method Not Allowed
*/
type DeleteProviderMethodNotAllowed struct {
	Payload *models.ServerError
}

func (o *DeleteProviderMethodNotAllowed) Error() string {
	return fmt.Sprintf("[DELETE /tf/provider/{name}][%d] deleteProviderMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *DeleteProviderMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProviderUnprocessableEntity creates a DeleteProviderUnprocessableEntity with default headers values
func NewDeleteProviderUnprocessableEntity() *DeleteProviderUnprocessableEntity {
	return &DeleteProviderUnprocessableEntity{}
}

/*DeleteProviderUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type DeleteProviderUnprocessableEntity struct {
	Payload *models.ServerError
}

func (o *DeleteProviderUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /tf/provider/{name}][%d] deleteProviderUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *DeleteProviderUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProviderInternalServerError creates a DeleteProviderInternalServerError with default headers values
func NewDeleteProviderInternalServerError() *DeleteProviderInternalServerError {
	return &DeleteProviderInternalServerError{}
}

/*DeleteProviderInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteProviderInternalServerError struct {
	Payload *models.ServerError
}

func (o *DeleteProviderInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /tf/provider/{name}][%d] deleteProviderInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteProviderInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
