// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteProviderConfigurationParams creates a new DeleteProviderConfigurationParams object
// with the default values initialized.
func NewDeleteProviderConfigurationParams() *DeleteProviderConfigurationParams {
	var ()
	return &DeleteProviderConfigurationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProviderConfigurationParamsWithTimeout creates a new DeleteProviderConfigurationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteProviderConfigurationParamsWithTimeout(timeout time.Duration) *DeleteProviderConfigurationParams {
	var ()
	return &DeleteProviderConfigurationParams{

		timeout: timeout,
	}
}

// NewDeleteProviderConfigurationParamsWithContext creates a new DeleteProviderConfigurationParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteProviderConfigurationParamsWithContext(ctx context.Context) *DeleteProviderConfigurationParams {
	var ()
	return &DeleteProviderConfigurationParams{

		Context: ctx,
	}
}

// NewDeleteProviderConfigurationParamsWithHTTPClient creates a new DeleteProviderConfigurationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteProviderConfigurationParamsWithHTTPClient(client *http.Client) *DeleteProviderConfigurationParams {
	var ()
	return &DeleteProviderConfigurationParams{
		HTTPClient: client,
	}
}

/*DeleteProviderConfigurationParams contains all the parameters to send to the API endpoint
for the delete provider configuration operation typically these are written to a http.Request
*/
type DeleteProviderConfigurationParams struct {

	/*ID
	  Configuration for a Terraform Provider

	*/
	ID string
	/*ProviderName
	  Terraform Provider ID

	*/
	ProviderName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete provider configuration params
func (o *DeleteProviderConfigurationParams) WithTimeout(timeout time.Duration) *DeleteProviderConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete provider configuration params
func (o *DeleteProviderConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete provider configuration params
func (o *DeleteProviderConfigurationParams) WithContext(ctx context.Context) *DeleteProviderConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete provider configuration params
func (o *DeleteProviderConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete provider configuration params
func (o *DeleteProviderConfigurationParams) WithHTTPClient(client *http.Client) *DeleteProviderConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete provider configuration params
func (o *DeleteProviderConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete provider configuration params
func (o *DeleteProviderConfigurationParams) WithID(id string) *DeleteProviderConfigurationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete provider configuration params
func (o *DeleteProviderConfigurationParams) SetID(id string) {
	o.ID = id
}

// WithProviderName adds the providerName to the delete provider configuration params
func (o *DeleteProviderConfigurationParams) WithProviderName(providerName string) *DeleteProviderConfigurationParams {
	o.SetProviderName(providerName)
	return o
}

// SetProviderName adds the providerName to the delete provider configuration params
func (o *DeleteProviderConfigurationParams) SetProviderName(providerName string) {
	o.ProviderName = providerName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProviderConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param provider-name
	if err := r.SetPathParam("provider-name", o.ProviderName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
