// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// DeleteProviderConfigurationReader is a Reader for the DeleteProviderConfiguration structure.
type DeleteProviderConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProviderConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteProviderConfigurationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteProviderConfigurationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewDeleteProviderConfigurationMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 422:
		result := NewDeleteProviderConfigurationUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteProviderConfigurationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteProviderConfigurationNoContent creates a DeleteProviderConfigurationNoContent with default headers values
func NewDeleteProviderConfigurationNoContent() *DeleteProviderConfigurationNoContent {
	return &DeleteProviderConfigurationNoContent{}
}

/*DeleteProviderConfigurationNoContent handles this case with default header values.

No Content
*/
type DeleteProviderConfigurationNoContent struct {
}

func (o *DeleteProviderConfigurationNoContent) Error() string {
	return fmt.Sprintf("[DELETE /tf/provider/{provider-name}/configuration/{id}][%d] deleteProviderConfigurationNoContent ", 204)
}

func (o *DeleteProviderConfigurationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProviderConfigurationNotFound creates a DeleteProviderConfigurationNotFound with default headers values
func NewDeleteProviderConfigurationNotFound() *DeleteProviderConfigurationNotFound {
	return &DeleteProviderConfigurationNotFound{}
}

/*DeleteProviderConfigurationNotFound handles this case with default header values.

Not Found
*/
type DeleteProviderConfigurationNotFound struct {
	Payload *models.ServerError
}

func (o *DeleteProviderConfigurationNotFound) Error() string {
	return fmt.Sprintf("[DELETE /tf/provider/{provider-name}/configuration/{id}][%d] deleteProviderConfigurationNotFound  %+v", 404, o.Payload)
}

func (o *DeleteProviderConfigurationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProviderConfigurationMethodNotAllowed creates a DeleteProviderConfigurationMethodNotAllowed with default headers values
func NewDeleteProviderConfigurationMethodNotAllowed() *DeleteProviderConfigurationMethodNotAllowed {
	return &DeleteProviderConfigurationMethodNotAllowed{}
}

/*DeleteProviderConfigurationMethodNotAllowed handles this case with default header values.

Method Not Allowed
*/
type DeleteProviderConfigurationMethodNotAllowed struct {
	Payload *models.ServerError
}

func (o *DeleteProviderConfigurationMethodNotAllowed) Error() string {
	return fmt.Sprintf("[DELETE /tf/provider/{provider-name}/configuration/{id}][%d] deleteProviderConfigurationMethodNotAllowed  %+v", 405, o.Payload)
}

func (o *DeleteProviderConfigurationMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProviderConfigurationUnprocessableEntity creates a DeleteProviderConfigurationUnprocessableEntity with default headers values
func NewDeleteProviderConfigurationUnprocessableEntity() *DeleteProviderConfigurationUnprocessableEntity {
	return &DeleteProviderConfigurationUnprocessableEntity{}
}

/*DeleteProviderConfigurationUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type DeleteProviderConfigurationUnprocessableEntity struct {
	Payload *models.ServerError
}

func (o *DeleteProviderConfigurationUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /tf/provider/{provider-name}/configuration/{id}][%d] deleteProviderConfigurationUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *DeleteProviderConfigurationUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProviderConfigurationInternalServerError creates a DeleteProviderConfigurationInternalServerError with default headers values
func NewDeleteProviderConfigurationInternalServerError() *DeleteProviderConfigurationInternalServerError {
	return &DeleteProviderConfigurationInternalServerError{}
}

/*DeleteProviderConfigurationInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteProviderConfigurationInternalServerError struct {
	Payload *models.ServerError
}

func (o *DeleteProviderConfigurationInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /tf/provider/{provider-name}/configuration/{id}][%d] deleteProviderConfigurationInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteProviderConfigurationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
