// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// GetProviderReader is a Reader for the GetProvider structure.
type GetProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewGetProviderAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetProviderNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetProviderInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProviderAccepted creates a GetProviderAccepted with default headers values
func NewGetProviderAccepted() *GetProviderAccepted {
	return &GetProviderAccepted{}
}

/*GetProviderAccepted handles this case with default header values.

OK
*/
type GetProviderAccepted struct {
	Payload *models.ResourceTfProvider
}

func (o *GetProviderAccepted) Error() string {
	return fmt.Sprintf("[GET /tf/provider/{id}][%d] getProviderAccepted  %+v", 202, o.Payload)
}

func (o *GetProviderAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceTfProvider)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProviderNotFound creates a GetProviderNotFound with default headers values
func NewGetProviderNotFound() *GetProviderNotFound {
	return &GetProviderNotFound{}
}

/*GetProviderNotFound handles this case with default header values.

Not Found
*/
type GetProviderNotFound struct {
	Payload *models.ServerError
}

func (o *GetProviderNotFound) Error() string {
	return fmt.Sprintf("[GET /tf/provider/{id}][%d] getProviderNotFound  %+v", 404, o.Payload)
}

func (o *GetProviderNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProviderInternalServerError creates a GetProviderInternalServerError with default headers values
func NewGetProviderInternalServerError() *GetProviderInternalServerError {
	return &GetProviderInternalServerError{}
}

/*GetProviderInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetProviderInternalServerError struct {
	Payload *models.ServerError
}

func (o *GetProviderInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tf/provider/{id}][%d] getProviderInternalServerError  %+v", 500, o.Payload)
}

func (o *GetProviderInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
