// Code generated by go-swagger; DO NOT EDIT.

package providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// ListProvidersReader is a Reader for the ListProviders structure.
type ListProvidersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProvidersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListProvidersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewListProvidersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListProvidersOK creates a ListProvidersOK with default headers values
func NewListProvidersOK() *ListProvidersOK {
	return &ListProvidersOK{}
}

/*ListProvidersOK handles this case with default header values.

OK
*/
type ListProvidersOK struct {
	Payload *models.ResponseListTfProviders
}

func (o *ListProvidersOK) Error() string {
	return fmt.Sprintf("[GET /tf/providers/][%d] listProvidersOK  %+v", 200, o.Payload)
}

func (o *ListProvidersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseListTfProviders)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProvidersInternalServerError creates a ListProvidersInternalServerError with default headers values
func NewListProvidersInternalServerError() *ListProvidersInternalServerError {
	return &ListProvidersInternalServerError{}
}

/*ListProvidersInternalServerError handles this case with default header values.

Internal Server Error
*/
type ListProvidersInternalServerError struct {
	Payload *models.ServerError
}

func (o *ListProvidersInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tf/providers/][%d] listProvidersInternalServerError  %+v", 500, o.Payload)
}

func (o *ListProvidersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
