// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// ListDeploymentsHandlerFunc turns a function with the right signature into a list deployments handler
type ListDeploymentsHandlerFunc func(ListDeploymentsParams, *models.ResourceAuthUser) middleware.Responder

// Handle executing the request and returning a response
func (fn ListDeploymentsHandlerFunc) Handle(params ListDeploymentsParams, principal *models.ResourceAuthUser) middleware.Responder {
	return fn(params, principal)
}

// ListDeploymentsHandler interface for that can handle valid list deployments params
type ListDeploymentsHandler interface {
	Handle(ListDeploymentsParams, *models.ResourceAuthUser) middleware.Responder
}

// NewListDeployments creates a new http.Handler for the list deployments operation
func NewListDeployments(ctx *middleware.Context, handler ListDeploymentsHandler) *ListDeployments {
	return &ListDeployments{Context: ctx, Handler: handler}
}

/*ListDeployments swagger:route GET /tf/stack/{id}/deployments stacks listDeployments

List the deployments for this stack

*/
type ListDeployments struct {
	Context *middleware.Context
	Handler ListDeploymentsHandler
}

func (o *ListDeployments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListDeploymentsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.ResourceAuthUser
	if uprinc != nil {
		principal = uprinc.(*models.ResourceAuthUser) // this is really a models.ResourceAuthUser, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
