// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// UndeployStackHandlerFunc turns a function with the right signature into a undeploy stack handler
type UndeployStackHandlerFunc func(UndeployStackParams, *models.ResourceAuthUser) middleware.Responder

// Handle executing the request and returning a response
func (fn UndeployStackHandlerFunc) Handle(params UndeployStackParams, principal *models.ResourceAuthUser) middleware.Responder {
	return fn(params, principal)
}

// UndeployStackHandler interface for that can handle valid undeploy stack params
type UndeployStackHandler interface {
	Handle(UndeployStackParams, *models.ResourceAuthUser) middleware.Responder
}

// NewUndeployStack creates a new http.Handler for the undeploy stack operation
func NewUndeployStack(ctx *middleware.Context, handler UndeployStackHandler) *UndeployStack {
	return &UndeployStack{Context: ctx, Handler: handler}
}

/*UndeployStack swagger:route DELETE /tf/stack/{id} stacks undeployStack

Undeploy a teraform module

*/
type UndeployStack struct {
	Context *middleware.Context
	Handler UndeployStackHandler
}

func (o *UndeployStack) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUndeployStackParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.ResourceAuthUser
	if uprinc != nil {
		principal = uprinc.(*models.ResourceAuthUser) // this is really a models.ResourceAuthUser, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
