// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/getlunaform/lunaform/models"
)

// ListResourceGroupsOKCode is the HTTP code returned for type ListResourceGroupsOK
const ListResourceGroupsOKCode int = 200

/*ListResourceGroupsOK OK

swagger:response listResourceGroupsOK
*/
type ListResourceGroupsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseListResources `json:"body,omitempty"`
}

// NewListResourceGroupsOK creates ListResourceGroupsOK with default headers values
func NewListResourceGroupsOK() *ListResourceGroupsOK {

	return &ListResourceGroupsOK{}
}

// WithPayload adds the payload to the list resource groups o k response
func (o *ListResourceGroupsOK) WithPayload(payload *models.ResponseListResources) *ListResourceGroupsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list resource groups o k response
func (o *ListResourceGroupsOK) SetPayload(payload *models.ResponseListResources) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListResourceGroupsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListResourceGroupsNotFoundCode is the HTTP code returned for type ListResourceGroupsNotFound
const ListResourceGroupsNotFoundCode int = 404

/*ListResourceGroupsNotFound Not Found

swagger:response listResourceGroupsNotFound
*/
type ListResourceGroupsNotFound struct {
}

// NewListResourceGroupsNotFound creates ListResourceGroupsNotFound with default headers values
func NewListResourceGroupsNotFound() *ListResourceGroupsNotFound {

	return &ListResourceGroupsNotFound{}
}

// WriteResponse to the client
func (o *ListResourceGroupsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
