---
builds:
  - binary: terraform-server
    main: ./server/cmd/terraform-server-server/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - binary: tfs-client
    main: ./cli/main.go
    ldflags:
      - -X github.com/drewsonne/terraform-server/cli/cmd.version={{.Version}}
git:
  short_hash: true

brew:
  name: terraform-server
  github:
    owner: drewsonne
    name: homebrew-tap
  install: |
    bin.install "terraform-server"
    bin.install "tfs-client"

nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS

  vendor: Drew J. Sonne
  homepage: https://github.com/drewsonne/terraform-server
  maintainer: Drew J. Sonne <drew.sonne@gmail.com>
  formats:
    - deb
    - rpm