// Code generated by go-swagger; DO NOT EDIT.

package modules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/drewsonne/lunarform/server/models"
)

// GetModuleReader is a Reader for the GetModule structure.
type GetModuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetModuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetModuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetModuleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetModuleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetModuleOK creates a GetModuleOK with default headers values
func NewGetModuleOK() *GetModuleOK {
	return &GetModuleOK{}
}

/*GetModuleOK handles this case with default header values.

OK
*/
type GetModuleOK struct {
	Payload *models.ResourceTfModule
}

func (o *GetModuleOK) Error() string {
	return fmt.Sprintf("[GET /tf/module/{id}][%d] getModuleOK  %+v", 200, o.Payload)
}

func (o *GetModuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceTfModule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModuleNotFound creates a GetModuleNotFound with default headers values
func NewGetModuleNotFound() *GetModuleNotFound {
	return &GetModuleNotFound{}
}

/*GetModuleNotFound handles this case with default header values.

Not Found
*/
type GetModuleNotFound struct {
	Payload *models.ServerError
}

func (o *GetModuleNotFound) Error() string {
	return fmt.Sprintf("[GET /tf/module/{id}][%d] getModuleNotFound  %+v", 404, o.Payload)
}

func (o *GetModuleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModuleInternalServerError creates a GetModuleInternalServerError with default headers values
func NewGetModuleInternalServerError() *GetModuleInternalServerError {
	return &GetModuleInternalServerError{}
}

/*GetModuleInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetModuleInternalServerError struct {
	Payload *models.ServerError
}

func (o *GetModuleInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tf/module/{id}][%d] getModuleInternalServerError  %+v", 500, o.Payload)
}

func (o *GetModuleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
