// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new resources API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for resources API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
ListResourceGroups List the root resource groups
*/
func (a *Client) ListResourceGroups(params *ListResourceGroupsParams) (*ListResourceGroupsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListResourceGroupsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "list-resource-groups",
		Method:             "GET",
		PathPattern:        "/",
		ProducesMediaTypes: []string{"application/vnd.terraform.server.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.terraform.server.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListResourceGroupsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListResourceGroupsOK), nil

}

/*
ListResources list resources API
*/
func (a *Client) ListResources(params *ListResourcesParams) (*ListResourcesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListResourcesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "list-resources",
		Method:             "GET",
		PathPattern:        "/{group}",
		ProducesMediaTypes: []string{"application/vnd.terraform.server.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.terraform.server.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListResourcesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListResourcesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
