// Code generated by go-swagger; DO NOT EDIT.

package state_backends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// NewCreateStateBackendParams creates a new CreateStateBackendParams object
// with the default values initialized.
func NewCreateStateBackendParams() *CreateStateBackendParams {
	var ()
	return &CreateStateBackendParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateStateBackendParamsWithTimeout creates a new CreateStateBackendParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateStateBackendParamsWithTimeout(timeout time.Duration) *CreateStateBackendParams {
	var ()
	return &CreateStateBackendParams{

		timeout: timeout,
	}
}

// NewCreateStateBackendParamsWithContext creates a new CreateStateBackendParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateStateBackendParamsWithContext(ctx context.Context) *CreateStateBackendParams {
	var ()
	return &CreateStateBackendParams{

		Context: ctx,
	}
}

// NewCreateStateBackendParamsWithHTTPClient creates a new CreateStateBackendParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateStateBackendParamsWithHTTPClient(client *http.Client) *CreateStateBackendParams {
	var ()
	return &CreateStateBackendParams{
		HTTPClient: client,
	}
}

/*CreateStateBackendParams contains all the parameters to send to the API endpoint
for the create state backend operation typically these are written to a http.Request
*/
type CreateStateBackendParams struct {

	/*TerraformStateBackend
	  A terraform state backend

	*/
	TerraformStateBackend *models.ResourceTfStateBackend

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create state backend params
func (o *CreateStateBackendParams) WithTimeout(timeout time.Duration) *CreateStateBackendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create state backend params
func (o *CreateStateBackendParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create state backend params
func (o *CreateStateBackendParams) WithContext(ctx context.Context) *CreateStateBackendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create state backend params
func (o *CreateStateBackendParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create state backend params
func (o *CreateStateBackendParams) WithHTTPClient(client *http.Client) *CreateStateBackendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create state backend params
func (o *CreateStateBackendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTerraformStateBackend adds the terraformStateBackend to the create state backend params
func (o *CreateStateBackendParams) WithTerraformStateBackend(terraformStateBackend *models.ResourceTfStateBackend) *CreateStateBackendParams {
	o.SetTerraformStateBackend(terraformStateBackend)
	return o
}

// SetTerraformStateBackend adds the terraformStateBackend to the create state backend params
func (o *CreateStateBackendParams) SetTerraformStateBackend(terraformStateBackend *models.ResourceTfStateBackend) {
	o.TerraformStateBackend = terraformStateBackend
}

// WriteToRequest writes these params to a swagger request
func (o *CreateStateBackendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.TerraformStateBackend != nil {
		if err := r.SetBodyParam(o.TerraformStateBackend); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
