// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/drewsonne/lunarform/server/models"
)

// GetStackReader is a Reader for the GetStack structure.
type GetStackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetStackOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetStackNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetStackInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStackOK creates a GetStackOK with default headers values
func NewGetStackOK() *GetStackOK {
	return &GetStackOK{}
}

/*GetStackOK handles this case with default header values.

OK
*/
type GetStackOK struct {
	Payload *models.ResourceTfStack
}

func (o *GetStackOK) Error() string {
	return fmt.Sprintf("[GET /tf/stack/{id}][%d] getStackOK  %+v", 200, o.Payload)
}

func (o *GetStackOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceTfStack)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStackNotFound creates a GetStackNotFound with default headers values
func NewGetStackNotFound() *GetStackNotFound {
	return &GetStackNotFound{}
}

/*GetStackNotFound handles this case with default header values.

Not Found
*/
type GetStackNotFound struct {
	Payload *models.ServerError
}

func (o *GetStackNotFound) Error() string {
	return fmt.Sprintf("[GET /tf/stack/{id}][%d] getStackNotFound  %+v", 404, o.Payload)
}

func (o *GetStackNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetStackInternalServerError creates a GetStackInternalServerError with default headers values
func NewGetStackInternalServerError() *GetStackInternalServerError {
	return &GetStackInternalServerError{}
}

/*GetStackInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetStackInternalServerError struct {
	Payload *models.ServerError
}

func (o *GetStackInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tf/stack/{id}][%d] getStackInternalServerError  %+v", 500, o.Payload)
}

func (o *GetStackInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
