// Code generated by go-swagger; DO NOT EDIT.

package resources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// ListResourcesReader is a Reader for the ListResources structure.
type ListResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewListResourcesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListResourcesOK creates a ListResourcesOK with default headers values
func NewListResourcesOK() *ListResourcesOK {
	return &ListResourcesOK{}
}

/*ListResourcesOK handles this case with default header values.

OK
*/
type ListResourcesOK struct {
	Payload *models.ResponseListResources
}

func (o *ListResourcesOK) Error() string {
	return fmt.Sprintf("[GET /{group}][%d] listResourcesOK  %+v", 200, o.Payload)
}

func (o *ListResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseListResources)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListResourcesNotFound creates a ListResourcesNotFound with default headers values
func NewListResourcesNotFound() *ListResourcesNotFound {
	return &ListResourcesNotFound{}
}

/*ListResourcesNotFound handles this case with default header values.

Not Found
*/
type ListResourcesNotFound struct {
	Payload *models.ServerError
}

func (o *ListResourcesNotFound) Error() string {
	return fmt.Sprintf("[GET /{group}][%d] listResourcesNotFound  %+v", 404, o.Payload)
}

func (o *ListResourcesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
