// Code generated by go-swagger; DO NOT EDIT.

package workspaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// CreateWorkspaceReader is a Reader for the CreateWorkspace structure.
type CreateWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateWorkspaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewCreateWorkspaceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateWorkspaceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreateWorkspaceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateWorkspaceOK creates a CreateWorkspaceOK with default headers values
func NewCreateWorkspaceOK() *CreateWorkspaceOK {
	return &CreateWorkspaceOK{}
}

/*CreateWorkspaceOK handles this case with default header values.

OK
*/
type CreateWorkspaceOK struct {
	Payload *models.ResourceTfWorkspace
}

func (o *CreateWorkspaceOK) Error() string {
	return fmt.Sprintf("[PUT /tf/workspace/{name}][%d] createWorkspaceOK  %+v", 200, o.Payload)
}

func (o *CreateWorkspaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceTfWorkspace)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWorkspaceCreated creates a CreateWorkspaceCreated with default headers values
func NewCreateWorkspaceCreated() *CreateWorkspaceCreated {
	return &CreateWorkspaceCreated{}
}

/*CreateWorkspaceCreated handles this case with default header values.

Created
*/
type CreateWorkspaceCreated struct {
	Payload *models.ResourceTfWorkspace
}

func (o *CreateWorkspaceCreated) Error() string {
	return fmt.Sprintf("[PUT /tf/workspace/{name}][%d] createWorkspaceCreated  %+v", 201, o.Payload)
}

func (o *CreateWorkspaceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceTfWorkspace)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWorkspaceBadRequest creates a CreateWorkspaceBadRequest with default headers values
func NewCreateWorkspaceBadRequest() *CreateWorkspaceBadRequest {
	return &CreateWorkspaceBadRequest{}
}

/*CreateWorkspaceBadRequest handles this case with default header values.

Bad Request
*/
type CreateWorkspaceBadRequest struct {
	Payload *models.ServerError
}

func (o *CreateWorkspaceBadRequest) Error() string {
	return fmt.Sprintf("[PUT /tf/workspace/{name}][%d] createWorkspaceBadRequest  %+v", 400, o.Payload)
}

func (o *CreateWorkspaceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWorkspaceInternalServerError creates a CreateWorkspaceInternalServerError with default headers values
func NewCreateWorkspaceInternalServerError() *CreateWorkspaceInternalServerError {
	return &CreateWorkspaceInternalServerError{}
}

/*CreateWorkspaceInternalServerError handles this case with default header values.

Internal Server Error
*/
type CreateWorkspaceInternalServerError struct {
	Payload *models.ServerError
}

func (o *CreateWorkspaceInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /tf/workspace/{name}][%d] createWorkspaceInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateWorkspaceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
