// Code generated by go-swagger; DO NOT EDIT.

package workspaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// DescribeWorkspaceReader is a Reader for the DescribeWorkspace structure.
type DescribeWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DescribeWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDescribeWorkspaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDescribeWorkspaceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDescribeWorkspaceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDescribeWorkspaceOK creates a DescribeWorkspaceOK with default headers values
func NewDescribeWorkspaceOK() *DescribeWorkspaceOK {
	return &DescribeWorkspaceOK{}
}

/*DescribeWorkspaceOK handles this case with default header values.

OK
*/
type DescribeWorkspaceOK struct {
	Payload *models.ResourceTfWorkspace
}

func (o *DescribeWorkspaceOK) Error() string {
	return fmt.Sprintf("[GET /tf/workspace/{name}][%d] describeWorkspaceOK  %+v", 200, o.Payload)
}

func (o *DescribeWorkspaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceTfWorkspace)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeWorkspaceNotFound creates a DescribeWorkspaceNotFound with default headers values
func NewDescribeWorkspaceNotFound() *DescribeWorkspaceNotFound {
	return &DescribeWorkspaceNotFound{}
}

/*DescribeWorkspaceNotFound handles this case with default header values.

Not Found
*/
type DescribeWorkspaceNotFound struct {
	Payload *models.ServerError
}

func (o *DescribeWorkspaceNotFound) Error() string {
	return fmt.Sprintf("[GET /tf/workspace/{name}][%d] describeWorkspaceNotFound  %+v", 404, o.Payload)
}

func (o *DescribeWorkspaceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDescribeWorkspaceInternalServerError creates a DescribeWorkspaceInternalServerError with default headers values
func NewDescribeWorkspaceInternalServerError() *DescribeWorkspaceInternalServerError {
	return &DescribeWorkspaceInternalServerError{}
}

/*DescribeWorkspaceInternalServerError handles this case with default header values.

Internal Server Error
*/
type DescribeWorkspaceInternalServerError struct {
	Payload *models.ServerError
}

func (o *DescribeWorkspaceInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tf/workspace/{name}][%d] describeWorkspaceInternalServerError  %+v", 500, o.Payload)
}

func (o *DescribeWorkspaceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
