// Code generated by go-swagger; DO NOT EDIT.

package workspaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// ListWorkspacesReader is a Reader for the ListWorkspaces structure.
type ListWorkspacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListWorkspacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListWorkspacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewListWorkspacesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewListWorkspacesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListWorkspacesOK creates a ListWorkspacesOK with default headers values
func NewListWorkspacesOK() *ListWorkspacesOK {
	return &ListWorkspacesOK{}
}

/*ListWorkspacesOK handles this case with default header values.

OK
*/
type ListWorkspacesOK struct {
	Payload *models.ResponseListTfWorkspaces
}

func (o *ListWorkspacesOK) Error() string {
	return fmt.Sprintf("[GET /tf/workspaces][%d] listWorkspacesOK  %+v", 200, o.Payload)
}

func (o *ListWorkspacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseListTfWorkspaces)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListWorkspacesNotFound creates a ListWorkspacesNotFound with default headers values
func NewListWorkspacesNotFound() *ListWorkspacesNotFound {
	return &ListWorkspacesNotFound{}
}

/*ListWorkspacesNotFound handles this case with default header values.

Not Found
*/
type ListWorkspacesNotFound struct {
}

func (o *ListWorkspacesNotFound) Error() string {
	return fmt.Sprintf("[GET /tf/workspaces][%d] listWorkspacesNotFound ", 404)
}

func (o *ListWorkspacesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListWorkspacesInternalServerError creates a ListWorkspacesInternalServerError with default headers values
func NewListWorkspacesInternalServerError() *ListWorkspacesInternalServerError {
	return &ListWorkspacesInternalServerError{}
}

/*ListWorkspacesInternalServerError handles this case with default header values.

Internal Server Error
*/
type ListWorkspacesInternalServerError struct {
	Payload *models.ServerError
}

func (o *ListWorkspacesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tf/workspaces][%d] listWorkspacesInternalServerError  %+v", 500, o.Payload)
}

func (o *ListWorkspacesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
