// Code generated by go-swagger; DO NOT EDIT.

package state_backends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// NewCreateStateBackendParams creates a new CreateStateBackendParams object
// no default values defined in spec.
func NewCreateStateBackendParams() CreateStateBackendParams {

	return CreateStateBackendParams{}
}

// CreateStateBackendParams contains all the bound params for the create state backend operation
// typically these are obtained from a http.Request
//
// swagger:parameters create-state-backend
type CreateStateBackendParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*A terraform state backend
	  In: body
	*/
	TerraformStateBackend *models.ResourceTfStateBackend
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateStateBackendParams() beforehand.
func (o *CreateStateBackendParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ResourceTfStateBackend
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("terraformStateBackend", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.TerraformStateBackend = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
