// Code generated by go-swagger; DO NOT EDIT.

package state_backends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/getlunaform/lunaform/models"
)

// CreateStateBackendCreatedCode is the HTTP code returned for type CreateStateBackendCreated
const CreateStateBackendCreatedCode int = 201

/*CreateStateBackendCreated OK

swagger:response createStateBackendCreated
*/
type CreateStateBackendCreated struct {

	/*
	  In: Body
	*/
	Payload *models.ResourceTfStateBackend `json:"body,omitempty"`
}

// NewCreateStateBackendCreated creates CreateStateBackendCreated with default headers values
func NewCreateStateBackendCreated() *CreateStateBackendCreated {

	return &CreateStateBackendCreated{}
}

// WithPayload adds the payload to the create state backend created response
func (o *CreateStateBackendCreated) WithPayload(payload *models.ResourceTfStateBackend) *CreateStateBackendCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create state backend created response
func (o *CreateStateBackendCreated) SetPayload(payload *models.ResourceTfStateBackend) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateStateBackendCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateStateBackendBadRequestCode is the HTTP code returned for type CreateStateBackendBadRequest
const CreateStateBackendBadRequestCode int = 400

/*CreateStateBackendBadRequest Bad Request

swagger:response createStateBackendBadRequest
*/
type CreateStateBackendBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ServerError `json:"body,omitempty"`
}

// NewCreateStateBackendBadRequest creates CreateStateBackendBadRequest with default headers values
func NewCreateStateBackendBadRequest() *CreateStateBackendBadRequest {

	return &CreateStateBackendBadRequest{}
}

// WithPayload adds the payload to the create state backend bad request response
func (o *CreateStateBackendBadRequest) WithPayload(payload *models.ServerError) *CreateStateBackendBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create state backend bad request response
func (o *CreateStateBackendBadRequest) SetPayload(payload *models.ServerError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateStateBackendBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
