// Code generated by go-swagger; DO NOT EDIT.

package state_backends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// ListStateBackendsHandlerFunc turns a function with the right signature into a list state backends handler
type ListStateBackendsHandlerFunc func(ListStateBackendsParams, *models.ResourceAuthUser) middleware.Responder

// Handle executing the request and returning a response
func (fn ListStateBackendsHandlerFunc) Handle(params ListStateBackendsParams, principal *models.ResourceAuthUser) middleware.Responder {
	return fn(params, principal)
}

// ListStateBackendsHandler interface for that can handle valid list state backends params
type ListStateBackendsHandler interface {
	Handle(ListStateBackendsParams, *models.ResourceAuthUser) middleware.Responder
}

// NewListStateBackends creates a new http.Handler for the list state backends operation
func NewListStateBackends(ctx *middleware.Context, handler ListStateBackendsHandler) *ListStateBackends {
	return &ListStateBackends{Context: ctx, Handler: handler}
}

/*ListStateBackends swagger:route GET /tf/state-backends state-backends listStateBackends

List TF State Backends

*/
type ListStateBackends struct {
	Context *middleware.Context
	Handler ListStateBackendsHandler
}

func (o *ListStateBackends) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListStateBackendsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.ResourceAuthUser
	if uprinc != nil {
		principal = uprinc.(*models.ResourceAuthUser) // this is really a models.ResourceAuthUser, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
