// Code generated by go-swagger; DO NOT EDIT.

package state_backends

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// UpdateStateBackendHandlerFunc turns a function with the right signature into a update state backend handler
type UpdateStateBackendHandlerFunc func(UpdateStateBackendParams, *models.ResourceAuthUser) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateStateBackendHandlerFunc) Handle(params UpdateStateBackendParams, principal *models.ResourceAuthUser) middleware.Responder {
	return fn(params, principal)
}

// UpdateStateBackendHandler interface for that can handle valid update state backend params
type UpdateStateBackendHandler interface {
	Handle(UpdateStateBackendParams, *models.ResourceAuthUser) middleware.Responder
}

// NewUpdateStateBackend creates a new http.Handler for the update state backend operation
func NewUpdateStateBackend(ctx *middleware.Context, handler UpdateStateBackendHandler) *UpdateStateBackend {
	return &UpdateStateBackend{Context: ctx, Handler: handler}
}

/*UpdateStateBackend swagger:route PUT /tf/state-backend/{id} state-backends updateStateBackend

Define a Terraform state backend

*/
type UpdateStateBackend struct {
	Context *middleware.Context
	Handler UpdateStateBackendHandler
}

func (o *UpdateStateBackend) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateStateBackendParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.ResourceAuthUser
	if uprinc != nil {
		principal = uprinc.(*models.ResourceAuthUser) // this is really a models.ResourceAuthUser, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
