/**
 * lunaform
 * This is a RESTful server for managing Terraform plan and apply jobs and the auditing of actions to approve those apply jobs. The inspiration for this project is the AWS CloudFormation API's. The intention is to implement a locking mechanism not only for the terraform state, but for the plan and apply of terraform modules. Once a `module` plan starts, it is instantiated as a `stack` within the nomencalture of `lunaform`. 
 *
 * OpenAPI spec version: 0.0.1-alpha
 * Contact: drew.sonne@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HalCurie', 'model/HalHref'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HalCurie'), require('./HalHref'));
  } else {
    // Browser globals (root is window)
    if (!root.Lunaform) {
      root.Lunaform = {};
    }
    root.Lunaform.HalRscLinks = factory(root.Lunaform.ApiClient, root.Lunaform.HalCurie, root.Lunaform.HalHref);
  }
}(this, function(ApiClient, HalCurie, HalHref) {
  'use strict';




  /**
   * The HalRscLinks model module.
   * @module model/HalRscLinks
   * @version 0.0.1-alpha
   */

  /**
   * Constructs a new <code>HalRscLinks</code>.
   * Links to this resources and documentation for this resource
   * @alias module:model/HalRscLinks
   * @class
   * @extends Object
   */
  var exports = function() {
    var _this = this;


    return _this;
  };

  /**
   * Constructs a <code>HalRscLinks</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HalRscLinks} obj Optional instance to populate.
   * @return {module:model/HalRscLinks} The populated <code>HalRscLinks</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ApiClient.constructFromObject(data, obj, 'HalHref');

      if (data.hasOwnProperty('curies')) {
        obj['curies'] = ApiClient.convertToType(data['curies'], [HalCurie]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/HalCurie>} curies
   */
  exports.prototype['curies'] = undefined;



  return exports;
}));


