// Code generated by go-swagger; DO NOT EDIT.

package workspaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// NewCreateWorkspaceParams creates a new CreateWorkspaceParams object
// no default values defined in spec.
func NewCreateWorkspaceParams() CreateWorkspaceParams {

	return CreateWorkspaceParams{}
}

// CreateWorkspaceParams contains all the bound params for the create workspace operation
// typically these are obtained from a http.Request
//
// swagger:parameters create-workspace,
type CreateWorkspaceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*A terraform workspace
	  Required: true
	  In: path
	*/
	Name string
	/*A terraform workspace
	  In: body
	*/
	TerraformWorkspace *models.ResourceTfWorkspace
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateWorkspaceParams() beforehand.
func (o *CreateWorkspaceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rName, rhkName, _ := route.Params.GetOK("name")
	if err := o.bindName(rName, rhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ResourceTfWorkspace
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("terraformWorkspace", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.TerraformWorkspace = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindName binds and validates parameter Name from path.
func (o *CreateWorkspaceParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Name = raw

	return nil
}
