// Code generated by go-swagger; DO NOT EDIT.

package workspaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// DescribeWorkspaceHandlerFunc turns a function with the right signature into a describe workspace handler
type DescribeWorkspaceHandlerFunc func(DescribeWorkspaceParams, *models.ResourceAuthUser) middleware.Responder

// Handle executing the request and returning a response
func (fn DescribeWorkspaceHandlerFunc) Handle(params DescribeWorkspaceParams, principal *models.ResourceAuthUser) middleware.Responder {
	return fn(params, principal)
}

// DescribeWorkspaceHandler interface for that can handle valid describe workspace params
type DescribeWorkspaceHandler interface {
	Handle(DescribeWorkspaceParams, *models.ResourceAuthUser) middleware.Responder
}

// NewDescribeWorkspace creates a new http.Handler for the describe workspace operation
func NewDescribeWorkspace(ctx *middleware.Context, handler DescribeWorkspaceHandler) *DescribeWorkspace {
	return &DescribeWorkspace{Context: ctx, Handler: handler}
}

/*DescribeWorkspace swagger:route GET /tf/workspace/{name} workspaces describeWorkspace

Describe a terraform workspace

*/
type DescribeWorkspace struct {
	Context *middleware.Context
	Handler DescribeWorkspaceHandler
}

func (o *DescribeWorkspace) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDescribeWorkspaceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.ResourceAuthUser
	if uprinc != nil {
		principal = uprinc.(*models.ResourceAuthUser) // this is really a models.ResourceAuthUser, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
