// Code generated by go-swagger; DO NOT EDIT.

package workspaces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// ListWorkspacesHandlerFunc turns a function with the right signature into a list workspaces handler
type ListWorkspacesHandlerFunc func(ListWorkspacesParams, *models.ResourceAuthUser) middleware.Responder

// Handle executing the request and returning a response
func (fn ListWorkspacesHandlerFunc) Handle(params ListWorkspacesParams, principal *models.ResourceAuthUser) middleware.Responder {
	return fn(params, principal)
}

// ListWorkspacesHandler interface for that can handle valid list workspaces params
type ListWorkspacesHandler interface {
	Handle(ListWorkspacesParams, *models.ResourceAuthUser) middleware.Responder
}

// NewListWorkspaces creates a new http.Handler for the list workspaces operation
func NewListWorkspaces(ctx *middleware.Context, handler ListWorkspacesHandler) *ListWorkspaces {
	return &ListWorkspaces{Context: ctx, Handler: handler}
}

/*ListWorkspaces swagger:route GET /tf/workspaces workspaces listWorkspaces

List approved terraform workspaces

*/
type ListWorkspaces struct {
	Context *middleware.Context
	Handler ListWorkspacesHandler
}

func (o *ListWorkspaces) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListWorkspacesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.ResourceAuthUser
	if uprinc != nil {
		principal = uprinc.(*models.ResourceAuthUser) // this is really a models.ResourceAuthUser, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
