// Code generated by go-swagger; DO NOT EDIT.

package modules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// DeleteModuleReader is a Reader for the DeleteModule structure.
type DeleteModuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteModuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteModuleNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 422:
		result := NewDeleteModuleUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteModuleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteModuleNoContent creates a DeleteModuleNoContent with default headers values
func NewDeleteModuleNoContent() *DeleteModuleNoContent {
	return &DeleteModuleNoContent{}
}

/*DeleteModuleNoContent handles this case with default header values.

No Content
*/
type DeleteModuleNoContent struct {
	Payload interface{}
}

func (o *DeleteModuleNoContent) Error() string {
	return fmt.Sprintf("[DELETE /tf/module/{id}][%d] deleteModuleNoContent  %+v", 204, o.Payload)
}

func (o *DeleteModuleNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteModuleUnprocessableEntity creates a DeleteModuleUnprocessableEntity with default headers values
func NewDeleteModuleUnprocessableEntity() *DeleteModuleUnprocessableEntity {
	return &DeleteModuleUnprocessableEntity{}
}

/*DeleteModuleUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type DeleteModuleUnprocessableEntity struct {
	Payload *models.ServerError
}

func (o *DeleteModuleUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /tf/module/{id}][%d] deleteModuleUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *DeleteModuleUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteModuleInternalServerError creates a DeleteModuleInternalServerError with default headers values
func NewDeleteModuleInternalServerError() *DeleteModuleInternalServerError {
	return &DeleteModuleInternalServerError{}
}

/*DeleteModuleInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteModuleInternalServerError struct {
	Payload *models.ServerError
}

func (o *DeleteModuleInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /tf/module/{id}][%d] deleteModuleInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteModuleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
