// Code generated by go-swagger; DO NOT EDIT.

package modules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new modules API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for modules API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreateModule Upload a Terraform module
*/
func (a *Client) CreateModule(params *CreateModuleParams, authInfo runtime.ClientAuthInfoWriter) (*CreateModuleCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateModuleParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "create-module",
		Method:             "POST",
		PathPattern:        "/tf/modules",
		ProducesMediaTypes: []string{"application/vnd.lunaform.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.lunaform.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateModuleReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreateModuleCreated), nil

}

/*
DeleteModule Delete a terraform module
*/
func (a *Client) DeleteModule(params *DeleteModuleParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteModuleNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteModuleParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "delete-module",
		Method:             "DELETE",
		PathPattern:        "/tf/module/{id}",
		ProducesMediaTypes: []string{"application/vnd.lunaform.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.lunaform.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteModuleReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteModuleNoContent), nil

}

/*
GetModule Get a Terraform module
*/
func (a *Client) GetModule(params *GetModuleParams, authInfo runtime.ClientAuthInfoWriter) (*GetModuleOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetModuleParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "get-module",
		Method:             "GET",
		PathPattern:        "/tf/module/{id}",
		ProducesMediaTypes: []string{"application/vnd.lunaform.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.lunaform.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetModuleReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetModuleOK), nil

}

/*
ListModules List TF modules
*/
func (a *Client) ListModules(params *ListModulesParams, authInfo runtime.ClientAuthInfoWriter) (*ListModulesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListModulesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "list-modules",
		Method:             "GET",
		PathPattern:        "/tf/modules",
		ProducesMediaTypes: []string{"application/vnd.lunaform.v1+json"},
		ConsumesMediaTypes: []string{"application/vnd.lunaform.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListModulesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListModulesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
