// Code generated by go-swagger; DO NOT EDIT.

package hal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HalHref hal href
// swagger:model hal-href
type HalHref struct {

	// href
	Href string `json:"href,omitempty"`
}

// Validate validates this hal href
func (m *HalHref) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HalHref) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HalHref) UnmarshalBinary(b []byte) error {
	var res HalHref
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
