// Code generated by go-swagger; DO NOT EDIT.

package tf

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/drewsonne/terraform-server/server/models"
)

// DeployStackReader is a Reader for the DeployStack structure.
type DeployStackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeployStackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewDeployStackCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeployStackBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeployStackCreated creates a DeployStackCreated with default headers values
func NewDeployStackCreated() *DeployStackCreated {
	return &DeployStackCreated{}
}

/*DeployStackCreated handles this case with default header values.

OK
*/
type DeployStackCreated struct {
	Payload *models.ResourceTfModule
}

func (o *DeployStackCreated) Error() string {
	return fmt.Sprintf("[POST /tf/stacks][%d] deployStackCreated  %+v", 201, o.Payload)
}

func (o *DeployStackCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceTfModule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeployStackBadRequest creates a DeployStackBadRequest with default headers values
func NewDeployStackBadRequest() *DeployStackBadRequest {
	return &DeployStackBadRequest{}
}

/*DeployStackBadRequest handles this case with default header values.

Bad Request
*/
type DeployStackBadRequest struct {
}

func (o *DeployStackBadRequest) Error() string {
	return fmt.Sprintf("[POST /tf/stacks][%d] deployStackBadRequest ", 400)
}

func (o *DeployStackBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
