// Code generated by go-swagger; DO NOT EDIT.

package modules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// NewCreateModuleParams creates a new CreateModuleParams object
// no default values defined in spec.
func NewCreateModuleParams() CreateModuleParams {

	return CreateModuleParams{}
}

// CreateModuleParams contains all the bound params for the create module operation
// typically these are obtained from a http.Request
//
// swagger:parameters create-module
type CreateModuleParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*A terraform module
	  In: body
	*/
	TerraformModule *models.ResourceTfModule
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateModuleParams() beforehand.
func (o *CreateModuleParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ResourceTfModule
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("terraformModule", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.TerraformModule = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
