// Code generated by go-swagger; DO NOT EDIT.

package modules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// DeleteModuleHandlerFunc turns a function with the right signature into a delete module handler
type DeleteModuleHandlerFunc func(DeleteModuleParams, *models.ResourceAuthUser) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteModuleHandlerFunc) Handle(params DeleteModuleParams, principal *models.ResourceAuthUser) middleware.Responder {
	return fn(params, principal)
}

// DeleteModuleHandler interface for that can handle valid delete module params
type DeleteModuleHandler interface {
	Handle(DeleteModuleParams, *models.ResourceAuthUser) middleware.Responder
}

// NewDeleteModule creates a new http.Handler for the delete module operation
func NewDeleteModule(ctx *middleware.Context, handler DeleteModuleHandler) *DeleteModule {
	return &DeleteModule{Context: ctx, Handler: handler}
}

/*DeleteModule swagger:route DELETE /tf/module/{id} modules deleteModule

Delete a terraform module

*/
type DeleteModule struct {
	Context *middleware.Context
	Handler DeleteModuleHandler
}

func (o *DeleteModule) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteModuleParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.ResourceAuthUser
	if uprinc != nil {
		principal = uprinc.(*models.ResourceAuthUser) // this is really a models.ResourceAuthUser, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
