// Code generated by go-swagger; DO NOT EDIT.

package modules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/getlunaform/lunaform/models"
)

// ListModulesOKCode is the HTTP code returned for type ListModulesOK
const ListModulesOKCode int = 200

/*ListModulesOK OK

swagger:response listModulesOK
*/
type ListModulesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseListTfModules `json:"body,omitempty"`
}

// NewListModulesOK creates ListModulesOK with default headers values
func NewListModulesOK() *ListModulesOK {

	return &ListModulesOK{}
}

// WithPayload adds the payload to the list modules o k response
func (o *ListModulesOK) WithPayload(payload *models.ResponseListTfModules) *ListModulesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list modules o k response
func (o *ListModulesOK) SetPayload(payload *models.ResponseListTfModules) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListModulesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListModulesNotFoundCode is the HTTP code returned for type ListModulesNotFound
const ListModulesNotFoundCode int = 404

/*ListModulesNotFound Not Found

swagger:response listModulesNotFound
*/
type ListModulesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ServerError `json:"body,omitempty"`
}

// NewListModulesNotFound creates ListModulesNotFound with default headers values
func NewListModulesNotFound() *ListModulesNotFound {

	return &ListModulesNotFound{}
}

// WithPayload adds the payload to the list modules not found response
func (o *ListModulesNotFound) WithPayload(payload *models.ServerError) *ListModulesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list modules not found response
func (o *ListModulesNotFound) SetPayload(payload *models.ServerError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListModulesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListModulesInternalServerErrorCode is the HTTP code returned for type ListModulesInternalServerError
const ListModulesInternalServerErrorCode int = 500

/*ListModulesInternalServerError Internal Server Error

swagger:response listModulesInternalServerError
*/
type ListModulesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ServerError `json:"body,omitempty"`
}

// NewListModulesInternalServerError creates ListModulesInternalServerError with default headers values
func NewListModulesInternalServerError() *ListModulesInternalServerError {

	return &ListModulesInternalServerError{}
}

// WithPayload adds the payload to the list modules internal server error response
func (o *ListModulesInternalServerError) WithPayload(payload *models.ServerError) *ListModulesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list modules internal server error response
func (o *ListModulesInternalServerError) SetPayload(payload *models.ServerError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListModulesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
