// Code generated by go-swagger; DO NOT EDIT.

package modules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/getlunaform/lunaform/models"
)

// ListModulesHandlerFunc turns a function with the right signature into a list modules handler
type ListModulesHandlerFunc func(ListModulesParams, *models.ResourceAuthUser) middleware.Responder

// Handle executing the request and returning a response
func (fn ListModulesHandlerFunc) Handle(params ListModulesParams, principal *models.ResourceAuthUser) middleware.Responder {
	return fn(params, principal)
}

// ListModulesHandler interface for that can handle valid list modules params
type ListModulesHandler interface {
	Handle(ListModulesParams, *models.ResourceAuthUser) middleware.Responder
}

// NewListModules creates a new http.Handler for the list modules operation
func NewListModules(ctx *middleware.Context, handler ListModulesHandler) *ListModules {
	return &ListModules{Context: ctx, Handler: handler}
}

/*ListModules swagger:route GET /tf/modules modules listModules

List TF modules

*/
type ListModules struct {
	Context *middleware.Context
	Handler ListModulesHandler
}

func (o *ListModules) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListModulesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.ResourceAuthUser
	if uprinc != nil {
		principal = uprinc.(*models.ResourceAuthUser) // this is really a models.ResourceAuthUser, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
