// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ResourceListTfStateBackend resource list tf state backend
// swagger:model resource-list-tf-state-backend
type ResourceListTfStateBackend struct {

	// state backends
	// Required: true
	StateBackends []*ResourceTfStateBackend `json:"state-backends"`
}

// Validate validates this resource list tf state backend
func (m *ResourceListTfStateBackend) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStateBackends(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourceListTfStateBackend) validateStateBackends(formats strfmt.Registry) error {

	if err := validate.Required("state-backends", "body", m.StateBackends); err != nil {
		return err
	}

	for i := 0; i < len(m.StateBackends); i++ {
		if swag.IsZero(m.StateBackends[i]) { // not required
			continue
		}

		if m.StateBackends[i] != nil {
			if err := m.StateBackends[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("state-backends" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResourceListTfStateBackend) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceListTfStateBackend) UnmarshalBinary(b []byte) error {
	var res ResourceListTfStateBackend
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
