// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/getlunaform/lunaform/models"
)

// ListStacksReader is a Reader for the ListStacks structure.
type ListStacksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListStacksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListStacksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewListStacksNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewListStacksInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListStacksOK creates a ListStacksOK with default headers values
func NewListStacksOK() *ListStacksOK {
	return &ListStacksOK{}
}

/*ListStacksOK handles this case with default header values.

OK
*/
type ListStacksOK struct {
	Payload *models.ResponseListTfStacks
}

func (o *ListStacksOK) Error() string {
	return fmt.Sprintf("[GET /tf/stacks][%d] listStacksOK  %+v", 200, o.Payload)
}

func (o *ListStacksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseListTfStacks)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListStacksNotFound creates a ListStacksNotFound with default headers values
func NewListStacksNotFound() *ListStacksNotFound {
	return &ListStacksNotFound{}
}

/*ListStacksNotFound handles this case with default header values.

Not Found
*/
type ListStacksNotFound struct {
	Payload *models.ServerError
}

func (o *ListStacksNotFound) Error() string {
	return fmt.Sprintf("[GET /tf/stacks][%d] listStacksNotFound  %+v", 404, o.Payload)
}

func (o *ListStacksNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListStacksInternalServerError creates a ListStacksInternalServerError with default headers values
func NewListStacksInternalServerError() *ListStacksInternalServerError {
	return &ListStacksInternalServerError{}
}

/*ListStacksInternalServerError handles this case with default header values.

Internal Server Error
*/
type ListStacksInternalServerError struct {
	Payload *models.ServerError
}

func (o *ListStacksInternalServerError) Error() string {
	return fmt.Sprintf("[GET /tf/stacks][%d] listStacksInternalServerError  %+v", 500, o.Payload)
}

func (o *ListStacksInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
