// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUndeployStackParams creates a new UndeployStackParams object
// with the default values initialized.
func NewUndeployStackParams() *UndeployStackParams {
	var ()
	return &UndeployStackParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUndeployStackParamsWithTimeout creates a new UndeployStackParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUndeployStackParamsWithTimeout(timeout time.Duration) *UndeployStackParams {
	var ()
	return &UndeployStackParams{

		timeout: timeout,
	}
}

// NewUndeployStackParamsWithContext creates a new UndeployStackParams object
// with the default values initialized, and the ability to set a context for a request
func NewUndeployStackParamsWithContext(ctx context.Context) *UndeployStackParams {
	var ()
	return &UndeployStackParams{

		Context: ctx,
	}
}

// NewUndeployStackParamsWithHTTPClient creates a new UndeployStackParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUndeployStackParamsWithHTTPClient(client *http.Client) *UndeployStackParams {
	var ()
	return &UndeployStackParams{
		HTTPClient: client,
	}
}

/*UndeployStackParams contains all the parameters to send to the API endpoint
for the undeploy stack operation typically these are written to a http.Request
*/
type UndeployStackParams struct {

	/*ID
	  Unique identifier for this stack

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the undeploy stack params
func (o *UndeployStackParams) WithTimeout(timeout time.Duration) *UndeployStackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the undeploy stack params
func (o *UndeployStackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the undeploy stack params
func (o *UndeployStackParams) WithContext(ctx context.Context) *UndeployStackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the undeploy stack params
func (o *UndeployStackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the undeploy stack params
func (o *UndeployStackParams) WithHTTPClient(client *http.Client) *UndeployStackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the undeploy stack params
func (o *UndeployStackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the undeploy stack params
func (o *UndeployStackParams) WithID(id string) *UndeployStackParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the undeploy stack params
func (o *UndeployStackParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UndeployStackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
